-- AlterTable
ALTER TABLE "OutfitClothing" ADD COLUMN     "scale" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "x" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "y" DOUBLE PRECISION NOT NULL DEFAULT 0;
